### ISSUE TITLE
Make a sidebar of contents

### ISSUE THREAD

**Issue by neozhaoliang** [joelgibson/lievis#1]
Hi, are you still developing this site? This is a beautiful project, would you consider adding a sidebar of contents, for example, at the left hand of the page, so that readers can navigate between the chapters more easily?

**Comment by joelgibson** [comment]
Hi Zhao, thanks for your interest! A sidebar sounds like a good idea - I never really thought of adding one before since the site grew as quite different pieces which were only loosely related. I'll have a think of a nice way to add one :)
